<?php

use Vindi\Payment\Block\Info\BankSlip;

/** @var $block BankSlip */
?>
<?php if (!$block->hasInvoice() && $block->canShowBankslipInfo() && $block->getPrintUrl()): ?>
    <dl class="payment-method">
        <dt class="title"><strong><?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?></strong></dt>
        <dd class="content">
            <br/>
            <p><strong><?php echo sprintf(__('Amount: %s'), $block->getFormattedAmount()) ?></strong></p>
            <p><?php echo sprintf(__('Print Url: %s'), '<a target="_blank" href="'. $block->getPrintUrl() . '">'. $block->getPrintUrl() . '</a>') ?></p>
            <?php if ($block->getDueDate()): ?>
                <p><?php echo sprintf(__('Due Date: %s'), $block->getDueDate()) ?></p>
            <?php endif; ?>
            <br/>
        </dd>
    </dl>
<?php else: ?>
    <span>
        <?= __($block->getPaymentMethodName()) ?>
    </span>
<?php endif; ?>
