<?php
/**
 * @var \Vindi\Payment\Block\Info\CardPix $block
 */
?>
<div class="card-pix-info">
    <?php if ($block->canShowCcInfo()) : ?>
        <dl class="payment-method cc-info">
            <dt class="title">
                <strong><?php echo $block->escapeHtml($block->getMethod()->getTitle()); ?></strong>
            </dt>
            <dd class="content">
                <p><?php echo sprintf(__('Cc Brand: %s'), $block->getCcBrand()); ?></p>
                <p><?php echo sprintf(__('Cc Owner: %s'), $block->getCcOwner()); ?></p>
                <p><?php echo sprintf(__('Cc Number: %s'), $block->getCcNumber()); ?></p>
                <p><?php echo sprintf(__('Installments: %sx'), $block->getCcInstallments()); ?></p>
            </dd>
        </dl>
    <?php endif; ?>

    <?php if (!$block->hasInvoice() && $block->canShowPixInfo() && $block->getQrCodePix() && $block->getQrcodeOriginalPath() && $block->getDaysToKeepWaitingPayment()) : ?>
        <dl class="payment-method pix-info">
            <dt class="title">
                <strong><?php echo $block->escapeHtml($block->getMethod()->getTitle()); ?></strong>
            </dt>
            <?php if ($block->canShowPixInfo()) : ?>
                <?php if ($block->getDaysToKeepWaitingPayment()) : ?>
                    <dd>
                        <p>
                            <strong><?php echo sprintf(__('Pay up: %s'), $block->getDaysToKeepWaitingPayment()); ?></strong>
                        </p>
                    </dd>
                <?php endif; ?>
                <dd class="content">
                    <?php if ($block->getQrCodePix()) : ?>
                        <object data="<?php echo $block->getQrCodePix(); ?>" type="image/svg+xml" class="qr-code" id="qrcode">
                            <p><?php echo $block->getQrCodeWarningMessage() ?: ''; ?></p>
                            <?php if ($block->getQrCodePix()) : ?>
                                <button
                                    id="vindi-pix-button-open"
                                    type="button"
                                    class="action primary checkout"
                                    title="Open QR Code Pix"
                                    onclick="window.open('<?php echo $block->getQrCodePix(); ?>', '_blank')">
                                    <?php echo __('Open QR Code'); ?>
                                </button>
                            <?php endif; ?>
                        </object>
                    <?php endif; ?>

                    <?php if ($block->getQrcodeOriginalPath()) : ?>
                        <p style="word-break: break-all;"><?php echo $block->getQrcodeOriginalPath(); ?></p>
                    <?php endif; ?>

                    <div data-bind="scope: 'vindiPix'">
                        <!-- ko template: getTemplate() --><!-- /ko -->
                    </div>
                </dd>
            <?php else : ?>
                <strong><?php echo __('Pix expired'); ?></strong></br>
                <a href="/vindiPayment/pix/renew?bill=<?php echo $block->getBillId(); ?>&order=<?php echo $block->getOrder()->getId(); ?>">
                    <button name="renew-pix"><?php echo __('Renew QR Code'); ?></button>
                </a>
            <?php endif; ?>
        </dl>

    <?php if ($block->getQrcodeOriginalPath()) : ?>
        <script type="text/x-magento-init">
            {
                "*": {
                    "Magento_Ui/js/core/app": {
                        "components": {
                            "vindiPix": {
                                "component": "Vindi_Payment/js/view/info/vindi-pix",
                                "qrCodeKey": <?php echo $block->getQrcodeOriginalPath(); ?>
            }
        }
    }
}
}
        </script>
    <?php endif; ?>
    <?php else: ?>
        <span><?php echo __($block->getPaymentMethodName()); ?></span>
    <?php endif; ?>
</div>
