<?php
/**
 * File: app/code/Vindi/Payment/view/frontend/templates/info/card_bankslippix.phtml
 *
 * @var \Vindi\Payment\Block\Info\CardBankslipPix $block
 */
?>
<div class="card-bankslippix-info">
    <dl class="payment-method info">
        <dt class="title">
            <strong><?php echo $block->escapeHtml($block->getMethod()->getTitle()); ?></strong>
        </dt>
    </dl>
    <hr>
    <?php if ($block->canShowCcInfo()) : ?>
        <dl class="payment-method cc-info">
            <dt class="title">
                <strong><?php echo $block->escapeHtml(__('Card')); ?></strong>
            </dt>
            <dd class="content">
                <p><?php echo sprintf(__('Cc Brand: %s'), $block->getCcBrand()); ?></p>
                <p><?php echo sprintf(__('Cc Owner: %s'), $block->getCcOwner()); ?></p>
                <p><?php echo sprintf(__('Cc Number: %s'), $block->getCcNumber()); ?></p>
                <p><?php echo sprintf(__('Installments: %sx'), $block->getCcInstallments()); ?></p>
            </dd>
        </dl>
    <?php endif; ?>

    <?php if (!$block->hasInvoice() && $block->canShowBolepixInfo() && $block->getQrCodeBolepix() && $block->getQrcodeOriginalPath() && $block->getDaysToKeepWaitingPayment()) : ?>
        <dl class="payment-method bolepix-info">
            <dt class="title">
                <strong><?php echo $block->escapeHtml(__('Bolepix')); ?></strong>
            </dt>
            <?php if ($block->canShowBolepixInfo()) : ?>
                <?php if ($block->getDaysToKeepWaitingPayment()) : ?>
                    <dd>
                        <p>
                            <strong><?php echo sprintf(__('Pay up: %s'), $block->getDaysToKeepWaitingPayment()); ?></strong>
                        </p>
                    </dd>
                <?php endif; ?>
                <dd class="content">
                    <?php if ($block->getQrCodeBolepix()) : ?>
                        <object data="<?php echo $block->getQrCodeBolepix(); ?>" type="image/svg+xml" class="qr-code" id="qrcode">
                            <p><?php echo $block->getQrCodeWarningMessage() ?: ''; ?></p>
                            <?php if ($block->getQrCodeBolepix()) : ?>
                                <button
                                    id="vindi-bolepix-button-open"
                                    type="button"
                                    class="action primary checkout"
                                    title="Open QR Code Bolepix"
                                    onclick="window.open('<?php echo $block->getQrCodeBolepix(); ?>', '_blank')">
                                    <?php echo __('Open QR Code'); ?>
                                </button>
                            <?php endif; ?>
                        </object>
                    <?php endif; ?>

                    <?php if ($block->getQrcodeOriginalPath()) : ?>
                        <p style="word-break: break-all;"><?php echo $block->getQrcodeOriginalPath(); ?></p>
                    <?php endif; ?>

                    <div data-bind="scope: 'vindiBolepix'">
                        <!-- ko template: getTemplate() --><!-- /ko -->
                    </div>
                </dd>
            <?php else : ?>
                <?php if (!$block->hasInvoice()) : ?>
                    <strong><?php echo __('Bolepix expired'); ?></strong></br>
                    <a href="/vindiPayment/bankslippix/renew?bill=<?php echo $block->getBillId(); ?>&order=<?php echo $block->getOrder()->getId(); ?>">
                        <button name="renew-bolepix"><?php echo __('Renew QR Code'); ?></button>
                    </a>
                <?php endif; ?>
            <?php endif; ?>
        </dl>

    <?php if ($block->getQrcodeOriginalPath()) : ?>
        <script type="text/x-magento-init">
            {
                "*": {
                    "Magento_Ui/js/core/app": {
                        "components": {
                            "vindiBolepix": {
                                "component": "Vindi_Payment/js/view/info/vindi-pix",
                                "qrCodeKey": <?php echo $block->getQrcodeOriginalPath(); ?>
            }
        }
    }
}
}
        </script>
    <?php endif; ?>
    <?php else: ?>
        <span><?php echo __($block->getPaymentMethodName()); ?></span>
    <?php endif; ?>
</div>
