<?php
/* @var \Vindi\Payment\Block\Info\CardPix $block */
?>
<div class="card-pix-info">
    <?php if ($block->canShowCcInfo()) : ?>
        <dl class="payment-method cc-info">
            <dt class="title">
                <strong><?= $block->escapeHtml($block->getMethod()->getTitle()) ?></strong>
            </dt>
            <dd class="content">
                <p><?= sprintf(__('Cc Brand: %s'), $block->getCcBrand()) ?></p>
                <p><?= sprintf(__('Cc Owner: %s'), $block->getCcOwner()) ?></p>
                <p><?= sprintf(__('Cc Number: %s'), $block->getCcNumber()) ?></p>
                <p><?= sprintf(__('Installments: %sx'), $block->getCcInstallments()) ?></p>
            </dd>
        </dl>
    <?php endif; ?>

    <?php if (!$block->hasInvoice() && $block->canShowPixInfo() && $block->getQrCodePix() && $block->getQrcodeOriginalPath() && $block->getDaysToKeepWaitingPayment()) : ?>
        <dl class="payment-method pix-info">
            <dt class="title">
                <strong><?= $block->escapeHtml($block->getMethod()->getTitle()) ?></strong>
            </dt>
            <?php if ($block->getDaysToKeepWaitingPayment()) : ?>
                <dd>
                    <p>
                        <strong><?= sprintf(__('Pay up: %s'), $block->getDaysToKeepWaitingPayment()) ?></strong>
                    </p>
                </dd>
            <?php endif; ?>
            <dd class="content">
                <?php if ($block->getQrCodePix()) : ?>
                    <object data="<?= $block->getQrCodePix() ?>" type="image/svg+xml" class="qr-code" id="qrcode">
                        <p><?= $block->getQrCodeWarningMessage() ?: '' ?></p>
                        <?php if ($block->getQrCodePix()) : ?>
                            <button
                                id="vindi-pix-button-open"
                                type="button"
                                class="action primary checkout"
                                title="Open QR Code Pix"
                                onclick="window.open('<?= $block->getQrCodePix() ?>', '_blank')">
                                <?= __('Open QR Code') ?>
                            </button>
                        <?php endif; ?>
                    </object>
                <?php endif; ?>

                <?php if ($block->getQrcodeOriginalPath()) : ?>
                    <p style="word-break: break-all;"><?= $block->getQrcodeOriginalPath() ?></p>
                <?php endif; ?>

                <div data-bind="scope: 'vindiPix'">
                    <!-- ko template: getTemplate() --><!-- /ko -->
                </div>
            </dd>
        </dl>
    <?php if ($block->getQrcodeOriginalPath()) : ?>
        <script type="text/x-magento-init">
            {
                "*": {
                    "Magento_Ui/js/core/app": {
                        "components": {
                            "vindiPix": {
                                "component": "Vindi_Payment/js/view/info/vindi-pix",
                                "qrCodeKey": <?= $block->getQrcodeOriginalPath() ?>
            }
        }
    }
}
}
        </script>
    <?php endif; ?>
    <?php else: ?>
        <strong><?= __('Pix expirado') ?></strong></br>
        <a href="/vindiPayment/pix/renew?bill=<?= $block->getBillId() ?>&order=<?= $block->getOrder()->getId() ?>">
            <button name="renew-pix"><?= __('Atualizar QR Code') ?></button>
        </a>
    <?php endif; ?>
</div>
